### ISSUE TITLE
报错x509

### ISSUE THREAD

**Issue by EVAyo** [pluveto/upgit#12]
`
Failed: Put "https://api.github.com/repos/***/****/contents/upgit/2022/02/upgit_20220202_1643738255.png": x509: certificate is valid for *.googlevideo.com, *.a1.googlevideo.com, *.bdn.dev, *.c.doc-0-0-sj.sj.googleusercontent.com, *.c.2mdn.net, *.dai.googlevideo.com, *.googlezip.net, *.gvt1.com, *.offline-maps.gvt1.com, *.snap.gvt1.com, *.gcpcdn.gvt1.com, xn--ngstr-lra8j.com, *.xn--ngstr-lra8j.com, i.ytimg.com, play-lh.googleusercontent.com, not api.github.com
`

**Comment by pluveto** [comment]
无法复现你的问题。请给出具体的使用场景和复现方法。
We are not able to reproduce this problem. Please give a specific usage scenario and reproduction steps.

**Comment by cnjn** [comment]
你这是linux系统吧？这是证书错误的原因，你可以试试安装curl和ca-certificates

**Comment by cnjn** [comment]
> `Failed: Put "https://api.github.com/repos/***/****/contents/upgit/2022/02/upgit_20220202_1643738255.png": x509: certificate is valid for *.googlevideo.com, *.a1.googlevideo.com, *.bdn.dev, *.c.doc-0-0-sj.sj.googleusercontent.com, *.c.2mdn.net, *.dai.googlevideo.com, *.googlezip.net, *.gvt1.com, *.offline-maps.gvt1.com, *.snap.gvt1.com, *.gcpcdn.gvt1.com, xn--ngstr-lra8j.com, *.xn--ngstr-lra8j.com, i.ytimg.com, play-lh.googleusercontent.com, not api.github.com`

你这是linux系统吧？这是证书错误的原因，你可以试试安装curl和ca-certificates

**Comment by EVAyo** [comment]
> certificates

windows的，我试试删除证书看看

**Comment by EVAyo** [comment]
> 无法复现你的问题。请给出具体的使用场景和复现方法。 We are not able to reproduce this problem. Please give a specific usage scenario and reproduction steps.

找到问题了，它不走系统代理，我给cmd配置代理后就可以上传了，请问可否添加一个配置代理的选项（http和socks5都可）呢

**Comment by pluveto** [comment]
> 找到问题了，它不走系统代理，我给cmd配置代理后就可以上传了，请问可否添加一个配置代理的选项（http和socks5都可）呢

用环境变量配置就行。单独增加配置反而会引起二义性。你可以用 bat 封装一下具体配置。
