### ISSUE TITLE
toml配置文件必须将[]方括号整行删掉才可正常使用

### ISSUE THREAD

**Issue by ocean0117** [pluveto/upgit#16]
我不知道是由于我哪里出了配置问题，但是在不注释掉全部的方括号行前，我是无法使用的，错误提示如下：
incorrect config: Username: zero value, Repo: zero value, PAT: zero value
疑似 [uploaders.github] 这一行出现问题

**Comment by pluveto** [comment]
软件版本是？





------------------ 原始邮件 ------------------
发件人: ocean0117 ***@***.***&gt;
发送时间: 2022年2月5日 22:00
收件人: pluveto/upgit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [pluveto/upgit] toml配置文件必须将[]方括号整行删掉才可正常使用 (Issue #16)





 
我不知道是由于我哪里出了配置问题，但是在不注释掉全部的方括号行前，我是无法使用的，错误提示如下：
 incorrect config: Username: zero value, Repo: zero value, PAT: zero value
 疑似 [uploaders.github] 这一行出现问题

**Comment by ocean0117** [comment]
0.1.6
是我傻了，麻烦您了

**Comment by pluveto** [comment]
没事儿，有问题欢迎提出
