### ISSUE TITLE
Integrates Obsidian with its Shell Commands plugin

### ISSUE THREAD

**Issue by emisjerry** [pluveto/upgit#17]
Hi, 

This is not an issue. I've made a video that introducing how to use Obsidian's Shell Commands plugin to integrate with upgit.
Maybe you will be interested:

[Obs#67] upgit- Use GitHub map: Quickly upload file to GitHub and insert url into Obsidian
https://youtu.be/nGII-khqm2o

**Comment by pluveto** [comment]
Glad to see your great exploration of using Upgit in Obsidian! 😘

By the way, since v0.2, Upgit has supported multiple uploaders, so please note that the new configuration file is not compatible with v0.1.x (and v0.1.6 is still stably works well)
