### ISSUE TITLE
mac 如何设置环境变量

### ISSUE THREAD

**Issue by DingyuanGao** [pluveto/upgit#23]
upgit 存放地址为 `/Users/Username/Library/Upgit/upgit`

环境变量中如何配置？

**Comment by pluveto** [comment]
https://github.com/pluveto/upgit#config-via-environment-variables

**Comment by DingyuanGao** [comment]
> https://github.com/pluveto/upgit#config-via-environment-variables

To access it from anywhere, add its directory to the PATH environment variable.

不好意思，没描述清楚，我的问题是macos的path的环境变量如何配置呢

**Comment by pluveto** [comment]
https://www.cnblogs.com/bjlhx/p/10623907.html





------------------ 原始邮件 ------------------
发件人: Panghh ***@***.***&gt;
发送时间: 2022年2月17日 12:33
收件人: pluveto/upgit ***@***.***&gt;
抄送: pluveto ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [pluveto/upgit] mac 如何设置环境变量 (Issue #23)





  
https://github.com/pluveto/upgit#config-via-environment-variables
  
To access it from anywhere, add its directory to the PATH environment variable.
 
不好意思，没描述清楚，我的问题是macos的path的环境变量如何配置呢

**Comment by pluveto** [comment]
若可执行文件名是  `/Users/Username/Library/Upgit/upgit`，则其目录是 dir = `/Users/Username/Library/Upgit/upgit`，把 dir 追加到 PATH 即可
