### ISSUE TITLE
能否支持上传剪贴板中的.png文件

### ISSUE THREAD

**Issue by XMB-7** [pluveto/upgit#27]
我目前在搭配obsidian(基于markdown的笔记软件)使用upgit, 所以很希望upgit能够实现批量处理图片.
比如将某一文件夹下的所有本地图片批量上传并将所有的url导出到剪贴板.

所以现场截图进行上传获取链接对我而言不太够用, 最好能支持将本地图片文件复制到剪贴板中然后进行上传然后再返回url至剪贴板. 我有尝试复制单一图片文件到剪贴板然后使用upgit上传, 失败的反馈信息是当前剪贴板中没有图像或格式不支持.
![图片](https://user-images.githubusercontent.com/65625632/156811162-00482c02-5b90-48df-889b-2c9274eb0dbf.png)

总而言之, 就是希望增加对本地图片通过剪贴板的处理, 如果能支持对本地图片的批量处理那就更好了.

**Comment by pluveto** [comment]
你使用的是 Windows 吗？可以选中文件后 Shift+RightClick 复制所有路径，然后 `upgit 文件1 文件2 文件3 -o markdown`

**Comment by XMB-7** [comment]
> 你使用的是 Windows 吗？可以选中文件后 Shift+RightClick 复制所有路径，然后 `upgit 文件1 文件2 文件3 -o markdown`

目前我使用upgit的场景是这样的. 在一个叫obsidian的类似于typra的md笔记软件里, 通过给"upgit :clipboard -f markdown"这条命令行语句设置一个快捷键(shift-v)来快捷地使用upgit. 设置完毕, 我在软件里直接按shift+v, 就能把剪贴板里的截图自动上传并在文档光标处插入回传的图片链接. 
所以基于我的这种用法, 被执行的命令行指令是不能变的, 如果每回都得手动输入文件123... 那用起来就太折磨了.
我所期望的是, 不管一个md文档之中有多少张本地图片, 我只要将它们复制到剪贴板, 然后执行upgit :clipboard -f markdown, upgit会在内部做一个遍历循环, 依次把剪贴板中各图片文件的本地链接都替换为远程链接. 这样我就可以继续通过使用快捷键shift-v来快速执行upgit :clipboard -f markdown并且一次完成对多张图片的批量处理了. 当前通过剪贴板上传图片只能处理单张图片感觉在功能上还是有一点局限的.
如果能费心增加相应功能的话, 相信upgit的易用性会更上一个台阶.

**Comment by pluveto** [comment]
Golang 不太好实现，要实现这个功能得重新发明一个 [Clipboard.GetFileDropList](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard.getfiledroplist)，有兴趣的话用 C# 写一个 Wrapper。

https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs

最简单的做法是用 AHK 读取剪贴板的路径并作为参数调用 upgit

**Comment by XMB-7** [comment]
> Golang 不太好实现，要实现这个功能得重新发明一个 [Clipboard.GetFileDropList](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard.getfiledroplist)，有兴趣的话用 C# 写一个 Wrapper。
> 
> https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs
> 
> 最简单的做法是用 AHK 读取剪贴板的路径并作为参数调用 upgit

好的, 谢谢. 我研究一下ahk, 知道这个但一直也没用过, 都是简单用点宏.

**Comment by PowerDi** [comment]
> > 你使用的是 Windows 吗？可以选中文件后 Shift+RightClick 复制所有路径，然后 `upgit 文件1 文件2 文件3 -o markdown`
> 
> 目前我使用upgit的场景是这样的. 在一个叫obsidian的类似于typora的md笔记软件里, 通过给"upgit :clipboard -f markdown"这条命令行语句设置一个快捷键(shift-v)来快捷地使用upgit. 设置完毕, 我在软件里直接按shift+v, 就能把剪贴板里的截图自动上传并在文档光标处插入回传的图片链接. 所以基于我的这种用法, 被执行的命令行指令是不能变的, 如果每回都得手动输入文件123... 那用起来就太折磨了. 我所期望的是, 不管一个md文档之中有多少张本地图片, 我只要将它们复制到剪贴板, 然后执行upgit :clipboard -f markdown, upgit会在内部做一个遍历循环, 依次把剪贴板中各图片文件的本地链接都替换为远程链接. 这样我就可以继续通过使用快捷键shift-v来快速执行upgit :clipboard -f markdown并且一次完成对多张图片的批量处理了. 当前通过剪贴板上传图片只能处理单张图片感觉在功能上还是有一点局限的. 如果能费心增加相应功能的话, 相信upgit的易用性会更上一个台阶.

感谢给了obsidian上面使用的启发，不得不说很是有想法啊
