### ISSUE TITLE
rename 占位符

### ISSUE THREAD

**Issue by Mr-xzq** [pluveto/upgit#28]
1. 缺少类似于{h}{m}{s} 时分秒的占位符；
2. 原始文件名 {fname} 不生效；
![image](https://user-images.githubusercontent.com/53166933/156956835-16664182-8e47-48b5-b0e4-9137fda819bd.png)

**Comment by pluveto** [comment]
已在下一个 Release 修复，如无问题可关闭 issue

**Comment by Mr-xzq** [comment]
噢噢， 好的好的， 这解决速度也太快了吧， 👍👍👍
