### ISSUE TITLE
自定义API支持

### ISSUE THREAD

**Issue by gclm** [pluveto/upgit#35]
目前无论是picgo 还是 upic 都支持自定义API。这样就不需要重复开发了，可以把大部分工作交给用户自定义

upic 示意：
![image](https://user-images.githubusercontent.com/27618687/162564392-3115b927-f66f-4052-ae66-31f89d6727a5.png)
picgo 示意：
![image](https://user-images.githubusercontent.com/27618687/162564409-df8fd21f-cfb7-4d54-8fc5-480136fdd4a6.png)

**Comment by pluveto** [comment]
这个功能是有的，这下面全是例子：https://github.com/pluveto/upgit/tree/main/extensions

**Comment by gclm** [comment]
你的意思，我添加一个类似配置,然后在config.toml 添加个选择就可以直接用吗？

**Comment by pluveto** [comment]
对，有兴趣的话可以帮忙整理出一个教程。俺太忙了

**Comment by gclm** [comment]
OK。我现在操作一下试试

**Comment by gclm** [comment]
好像有点问题：

![image](https://user-images.githubusercontent.com/27618687/162565296-3ead98c6-68b3-47b9-9c3e-b9ee23dd3665.png)
![image](https://user-images.githubusercontent.com/27618687/162565320-7b2a8062-c50a-49ff-904b-31fe985214c4.png)
![image](https://user-images.githubusercontent.com/27618687/162565339-696107a9-6aa2-4d3b-9239-e7a2c44e1176.png)

**Comment by pluveto** [comment]
放到你的 extensions 目录

**Comment by gclm** [comment]
![image](https://user-images.githubusercontent.com/27618687/162601790-f4385de9-db37-4415-a0b9-f2b43eaaa977.png)
![image](https://user-images.githubusercontent.com/27618687/162601805-5c566212-abd9-41e4-8f67-17fd74527aed.png)

是需要我在fork 一个项目才行吗？

**Comment by pluveto** [comment]
放在那个目录之后就可以了

**Comment by jeffxjh** [comment]
请问一下，我也遇到了这个问题，
![image](https://user-images.githubusercontent.com/44387640/168421280-0f9864e4-a2d7-407f-953e-03d03b2f34c9.png)
![image](https://user-images.githubusercontent.com/44387640/168421304-3bb538dc-fdcd-444d-86b8-64b9f908cb49.png)
![image](https://user-images.githubusercontent.com/44387640/168421319-e78ab61c-9634-4a67-af37-5999492b9369.png)
最后怎么解决的？

**Comment by pluveto** [comment]
> 请问一下，我也遇到了这个问题， ![image](https://user-images.githubusercontent.com/44387640/168421280-0f9864e4-a2d7-407f-953e-03d03b2f34c9.png) ![image](https://user-images.githubusercontent.com/44387640/168421304-3bb538dc-fdcd-444d-86b8-64b9f908cb49.png) ![image](https://user-images.githubusercontent.com/44387640/168421319-e78ab61c-9634-4a67-af37-5999492b9369.png) 最后怎么解决的？

本地的不用下载。
