### ISSUE TITLE
使用 lskypro 扩展报错 `Post "7bu.top/api/upload": unsupported protocol scheme ""`

### ISSUE THREAD

**Issue by wchen9** [pluveto/upgit#36]
版本是当前最新release。

**Comment by pluveto** [comment]
你忘了写 protocol scheme

**Comment by wchen9** [comment]
> 

加前缀 https:// 一样报错

**Comment by wchen9** [comment]
> 

抱歉，昨晚试的加 https:// 也报错了，刚刚试了一下发现报的是另一个错了。

`Failed: rawUrl path is not valid: for path data.url, key url not found`

**Comment by wchen9** [comment]
![image](https://user-images.githubusercontent.com/2026700/162600852-240fe211-ec9e-4230-b834-dda785f7c2e0.png)
使用接口调用正常，数据返回的 data.url 也有数据，不知道为啥上传不成功。`uploaders.lskypro` 中配置了 token 跟 host。

**Comment by wchen9** [comment]
破案了，repo里面提供的lskypro.jsonc 里面的body 写的不对，需要 加一个
```
"token": {
    "type": "string",
    "value": "$(ext_config.token)"
}
```

**Comment by pluveto** [comment]
欢迎 PR
