### ISSUE TITLE
[报错]Typora上传测试报: dial tcp 104.21.235.65:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by jixishi** [pluveto/upgit#45]
![image](https://user-images.githubusercontent.com/57534147/183555568-6bc12bb2-438f-4200-847f-d3df285174f8.png)

**Comment by pluveto** [comment]
看起来是接口加了鉴权，建议换个图床看看---- On Tue, 2022-08-09 11:13:35  ***@***.***> wrote ----

**Comment by jixishi** [comment]
命令行使用是正常的，只在Typora里报这个错误

**Comment by jixishi** [comment]
![image](https://user-images.githubusercontent.com/57534147/183556684-310ddbc9-afec-44dc-9243-832aea4cfcbd.png)

**Comment by pluveto** [comment]
你试试打开 typora 用 sudo---- On Tue, 2022-08-09 11:21:12  ***@***.***> wrote ----  
命令行使用是正常的，只在Typora里报这个错误

**Comment by jixishi** [comment]
刚刚试了下好像是代理问题全局代理正常。。。
