### ISSUE TITLE
能否支持bilibili图床

### ISSUE THREAD

**Issue by MC-dusk** [pluveto/upgit#46]
注意到这个项目是go语言，之前使用过https://github.com/xlzy520/typora-plugin-bilibili 这个B站图床上传插件，也是go语言，MIT许可，不知道容不容易合并。

**Comment by pluveto** [comment]
看起来逻辑比较简单，不用写代码就能实现。可以参考一下 https://github.com/pluveto/upgit/tree/main/extensions

**Comment by pluveto** [comment]
This feature may lead to legal problems and will not be supported.
