### ISSUE TITLE
win11 upgitrc 不可用

### ISSUE THREAD

**Issue by 4ft35t** [pluveto/upgit#47]
Upgit v0.2.16

用户目录下 `.upgit.config.toml` 可以正常使用

`PS C:\Users\xxx> mv .\.upgit.config.toml .\.config\upgitrc` 移动到 `.config\upgitrc` 后报错 

`no config file found`

scoop 也在用 .config 目录做配置，想把配置文件汇聚到一起。

**Comment by pluveto** [comment]
试一下新版本

**Comment by 4ft35t** [comment]
确认可以工作了
