### ISSUE TITLE
支持又拍云的插件找不到了

### ISSUE THREAD

**Issue by XyoZang** [pluveto/upgit#49]
哪个是又拍云的上传扩展呀，找了半天没找到

**Comment by pluveto** [comment]
内置的。

**Comment by ZhangXQA** [comment]
配置文件里也没有找到又拍云的相关配置呢

**Comment by pluveto** [comment]
可以参考 https://github.com/pluveto/upgit/blob/main/lib/upyun/uploader.go

**Comment by pluveto** [comment]
不记得为啥没有配置了，可能是没写完或者有 bug，也可能不是。等有时间再看看

**Comment by ZhangXQA** [comment]
嗯呢，我先看看能不能配置出来
