### ISSUE TITLE
上传有大小限制吗？

### ISSUE THREAD

**Issue by cksspk** [pluveto/upgit#50]
传不上去，日志如下：

2022-09-14 08:51:07.915924 +0800 CST m=+0.000319876[INFO ] Started
2022-09-14 08:51:07.925968 +0800 CST m=+0.010363584[ERROR] abort: invalid file to upload /var/folders/hc/my4442h94j5983yx1xdkrsk00000gn/T//upgit_tmp_1663116667916137.png: file size is larger than 5242880 bytes
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.18.0-beta1/x64/src/runtime/debug/stack.go:24 +0x68
github.com/pluveto/upgit/lib/xlog.Verbose.Log({0xc8?, 0x5d?, {0x14000156210?, 0x10?}, 0x140001a8000?}, {0x1023575ad, 0x8}, {0x140001aa000?, 0x1023526cc?}, {0x0?, ...})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:55 +0xf8
github.com/pluveto/upgit/lib/xlog.Verbose.Error(...)
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:44
github.com/pluveto/upgit/lib/xlog.AbortErr({0x102458c68?, 0x1400011aee0?})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:93 +0xe8
main.validArgs()
	/Users/runner/work/upgit/upgit/main.go:182 +0x310
main.mainCommand()
	/Users/runner/work/upgit/upgit/main.go:57 +0xa0
main.main()
	/Users/runner/work/upgit/upgit/main.go:40 +0xb8

这种情况如何处理呢？支持修改大小上限值吗

**Comment by pluveto** [comment]
可以查阅命令帮助修改上限---- On Wed, 2022-09-14 08:52:45  ***@***.***> wrote ----  
传不上去，日志如下：  
2022-09-14 08:51:07.915924 +0800 CST m=+0.000319876[INFO ] Started  
2022-09-14 08:51:07.925968 +0800 CST m=+0.010363584[ERROR] abort: invalid file to upload /var/folders/hc/my4442h94j5983yx1xdkrsk00000gn/T//upgit_tmp_1663116667916137.png: file size is larger than 5242880 bytes  
goroutine 1 [running]:  
runtime/debug.Stack()  
/Users/runner/hostedtoolcache/go/1.18.0-beta1/x64/src/runtime/debug/stack.go:24 +0x68  
github.com/pluveto/upgit/lib/xlog.Verbose.Log({0xc8?, 0x5d?, {0x14000156210?, 0x10?}, 0x140001a8000?}, {0x1023575ad, 0x8}, {0x140001aa000?, 0x1023526cc?}, {0x0?, ...})  
/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:55 +0xf8  
github.com/pluveto/upgit/lib/xlog.Verbose.Error(...)  
/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:44  
github.com/pluveto/upgit/lib/xlog.AbortErr({0x102458c68?, 0x1400011aee0?})  
/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:93 +0xe8  
main.validArgs()  
/Users/runner/work/upgit/upgit/main.go:182 +0x310  
main.mainCommand()  
/Users/runner/work/upgit/upgit/main.go:57 +0xa0  
main.main()  
/Users/runner/work/upgit/upgit/main.go:40 +0xb8  
这种情况如何处理呢？支持修改大小上限值吗

**Comment by kevzcr** [comment]
以前用picgo-core上传文件失败，记着提示超过25Mb了。
