### ISSUE TITLE
能不能设置一个option 一直开启rename

### ISSUE THREAD

**Issue by Jechin** [pluveto/upgit#53]
想在使用-t的情况下仍然适用raname rule

**Comment by Jechin** [comment]
use -t and rename rule at same time

**Comment by pluveto** [comment]
Good suggestion

**Comment by jerryc127** [comment]
有兴趣实现么？

> Good suggestion

**Comment by pluveto** [comment]
rename 其实就是指定了路径，或者说路径分隔符就是 name 的一部分。所以要实现的话需要有一个合理的设计。
