### ISSUE TITLE
unexpected end of json input

### ISSUE THREAD

**Issue by yakoocy** [pluveto/upgit#54]
unexpected end of json input

**Comment by pluveto** [comment]
gitee官方已禁止使用外链，死心吧---- On Mon, 2022-11-14 20:59:58  ***@***.***> wrote ----  
新手小白，是json文件里的"url": "https://gitee.com/api/v5/repos/$(ext_config.username)/$(ext_config.repo)/contents/$(task.target_path)",要改成自己的库名称吗，$(task.target_path)这个是指什么啊

**Comment by yakoocy** [comment]
好吧  谢谢
