### ISSUE TITLE
剪贴板能否增强一下

### ISSUE THREAD

**Issue by kevzcr** [pluveto/upgit#55]
剪贴板只能上传PNG图片，能否也可以上传其他格式文件。上传其他格式不得不用命令行逐条进行，远没有上传图片时，快捷键一键上传来得方便，特麻烦。

**Comment by zbb7001** [comment]
> In consideration

几乎隔两天就来看一下，期待更新啊！

**Comment by pluveto** [comment]
This feature has been supported, download the latest release to try.
