### ISSUE TITLE
macos下载之后不可运行，格式为文稿格式

### ISSUE THREAD

**Issue by wowguoqing** [pluveto/upgit#64]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/29644235/220286783-fbc9d742-8dca-4547-961b-01c6e1e9100c.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/29644235/220286860-13d93768-4db1-4982-b7bc-531fc88780b1.png">

**Comment by wowguoqing** [comment]
下载文件为upgit_macos_arm64，电脑是m1 mac

**Comment by pluveto** [comment]
请问您的版本是？

**Comment by pluveto** [comment]
I've tested on my mac m1, not reproduced

**Comment by wowguoqing** [comment]
> 



I has executed chmod +x . It`s work ~.   Thank you ~!
