### ISSUE TITLE
有人能帮忙看看配置文件哪里错了么，总是报错

### ISSUE THREAD

**Issue by lb8023lyy** [pluveto/upgit#66]
config.toml
以下为文件内容
default_uploader = "github"
branch = "main"
pat = "ghp_TikdmhPW9qeIXgGxxxxxxxxxxxxxxxxxxx" #此处隐藏
rename = "{year}/{month}/upgit_{year}{month}{day}_{unix_ts}{ext}"
repo = "lb8023lyy/Image"
username = "lb8023lyy"
[replacements]
"raw.githubusercontent.com" = "cdn.jsdelivr.net/gh"
"/main" = "@main"
[output-formats]
"markdown-simple" = "![]({url})"

**Comment by pluveto** [comment]
日志提供一下  ---- On Sun, 2023-04-02 09:46:12  ***@***.***> wrote ----  
config.toml 
以下为文件内容 
default_uploader = "github" 
branch = "main" 
pat = "ghp_TikdmhPW9qeIXgGxxxxxxxxxxxxxxxxxxx" #此处隐藏 
rename = "{year}/{month}/upgit_{year}{month}{day}_{unix_ts}{ext}" 
repo = "lb8023lyy/Image" 
username = "lb8023lyy" 
[replacements] 
"raw.githubusercontent.com" = "cdn.jsdelivr.net/gh" 
"/main" = ***@***.***" 
[output-formats] 
"markdown-simple" = ""
