### ISSUE TITLE
upgit 1.png报错

### ISSUE THREAD

**Issue by mxlt02** [pluveto/upgit#7]
=>:upgit 1.png
panic: assignment to entry in nil map

goroutine 1 [running]:
main.main()
        /home/runner/work/upgit/upgit/main.go:91 +0x31c

**Comment by mxlt02** [comment]
0.1.5 upgit_win_amd64.exe

**Comment by pluveto** [comment]
已修复，请等待 Github Action 发布新的 Release

**Comment by pluveto** [comment]
试一下可以了吗？
https://github.com/pluveto/upgit/releases/tag/v0.1.6

**Comment by mxlt02** [comment]
可以了
