### ISSUE TITLE
What's the version `v0.2.24-build`?

### ISSUE THREAD

**Issue by suzuki-shunsuke** [pluveto/upgit#84]
https://github.com/pluveto/upgit/releases/tag/v0.2.24-build
https://github.com/pluveto/upgit/releases/tag/v0.2.24

<img width="722" alt="image" src="https://github.com/pluveto/upgit/assets/13323303/e847ec4f-2fe0-4dbd-8de8-de60aca09174">

<img width="1188" alt="image" src="https://github.com/pluveto/upgit/assets/13323303/6727ffc7-1751-4b0e-a11a-b8a4aecb3978">

I noticed the release v0.2.24 doesn't have pre built binaries and the version v0.2.24-build have them instead.
These versions are associated with the same commit hash. https://github.com/pluveto/upgit/commit/6b8365ab6ed5af833a069fbef1c600c12e6994d6
What's `*-build`? Why is this version necessary?

**Comment by suzuki-shunsuke** [comment]
Seems like v0.2.24 was released by GitHub Actions. https://github.com/pluveto/upgit/actions/runs/9867934413
But I can't find the workflow run associated with v0.2.24-build. 🤔

https://github.com/pluveto/upgit/actions

<img width="1321" alt="image" src="https://github.com/pluveto/upgit/assets/13323303/9b51b411-7d56-4b96-9490-1ac9fa9ebaec">

**Comment by pluveto** [comment]
![image](https://github.com/pluveto/upgit/assets/50045289/4ade9407-5298-4722-b394-fc4d56a5fabd)

This was due to some bugs in my release workflow configuration that caused the generated tag to be main instead of a specific version number, so I manually changed main to v0.2.24-build.

I'll follow up with a fix.

**Comment by pluveto** [comment]
Fixed in https://github.com/pluveto/upgit/commit/53f36b960b228907ee9cc16df64d1186c6d6e6e1

https://github.com/pluveto/upgit/releases/tag/v0.2.25

**Comment by suzuki-shunsuke** [comment]
Thank you for fixing quickly!
